version: '3'
services:
  typescript:
    container_name: typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/app
    tty: true
    stdin_open: true